# Generated by Django 2.2.16 on 2022-07-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20220717_1428'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='author_title',
        ),
    ]
